version: '3.8'
services:
  app:
    build: .
    restart: always
    env_file: .env
    links:
      - db
    expose:
      - "5550"
    volumes:
      - web-files:/python-docker
  db:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0 --default_authentication_plugin=mysql_native_password
    expose:
      - "3306"
    environment:
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=ied
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - database-files:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:ro
#  nginx:
#    build: ./nginx
#    restart: always
#    ports:
#      - "80:80"
  redis:
    image: "redis/redis-stack:latest"
    ports:
      - "6379"
    volumes:
      - cache-files:/data


volumes:
  web-files:
  database-files:
  cache-files:

 