version: '3.8'
services:
  app:
    build: .
    restart: always
    env_file: .env
    links:
      - db
#    expose:
#      - "5550"
    volumes:
      - web-files:/python-docker
    ports:
      - "5555:5550"
  db:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    expose:
      - "3306"
    environment:
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=ied
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - database-files:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:ro
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
  redis:
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
      - "60888:8001"
    volumes:
      - cache-files:/data
  # 正式环境请注释或删除掉phpmyadmin环境，切记！
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "60880:80"

volumes:
  web-files:
  database-files:
  cache-files:

 